[workspace]
members = ["raydium_amm_poc", "app"]

[workspace.dependencies]
anchor-lang = "0.29.0"
solana-client = "<1.17.0"
solana-sdk = "<1.17.0"
raydium_amm = { git = "https://github.com/raydium-io/raydium-amm", default-features = false, features = [
    "client",
] }
